### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]

### ISSUE THREAD

**Issue by stevenKirill** [eslint/eslint-scope#108]
Hi, I have a question, I try to build my project and get an error. Please help me.

[webpack-cli] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/referencer' is not defined by "exports" in node_modules/eslint-scope/package.json

Same with npm run lint

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Failed to load plugin '@typescript-eslint' declared in '.eslintrc » configs/typescript.js': Package subpath './lib/definition' is not defined by "exports" in node_modules/eslint-scope/package.json

my node version is 16.14.0, npm version: 8.3.1.

 I need to install my deps by npm ci command, coz some new versions I cant use due to company policy.  So I used this package https://www.npmjs.com/package/npm-force-resolutions to force and use version 7.2.0, or 7.2.1, I can't use 7.2.2 coz its fresh version and released just 10 days ago. Is there any solutions not to delete node_modules and reintall all deps by npm i, I just asy npm ci to keep my lock file constant.

**Comment by stevenKirill** [comment]
Thank you for your help! But I need to fix dependencies somehow, because I have a company private nexus registry and I can't install all deps, only kinda versions which have been released not earlier than 14 days.

**Comment by nzakas** [comment]
Not related to this package, so closing.
