### ISSUE TITLE
Better support for parsers such as typescript and babel-eslint

### ISSUE THREAD

**Issue by soda0289** [eslint/eslint-scope#17]
I made some comments [here](https://github.com/eslint/eslint/issues/6364#issuecomment-279505828) about how we can improve eslint-scope to accommodate parsers such typescript-eslint-parser and babel-eslint.

I'd like to propose some ideas for some basic enhancements:

1) Should we remove the dependency on estraverse and esrecurse. Estraverse is only used to provide a syntax list and eslint-scope does not call any of its functions. We could hard code this syntax list is since it is provied by estree. Esrecurse is only used for two function calls, visit() and visitChildren(), which we could move into this project to give us more control of the visiting behavior and fallback handling.

2) I can understand not wanting to have parser provide a Referencer object as this would lead to lots of extra work for parsers. Could we instead provide an object that would allow eslint-scope to treat/scope node that are unknown in a similar way as known nodes. For example in typescript we have abstract classes would it be possible to say scope this Abstract Class node like a Class node. Or treat Abstract Class methods, with bodies, like Class methods.

**Comment by nzakas** [comment]
Closing due to age.

**Comment by bradzacher** [comment]
For posterity's sake:

@typescript-eslint now has its own fork of this scope manager which adds full support for TypeScript features:
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/scope-manager
