### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint-scope#23]
@JamesHenry @corbinu @soda0289 Is this repository now ready to be published? We want to replace `escope` with this fork in ESLint for version 4.0 and for that we need to publish it to NPM. I can do a release if you give me a go-ahead.

**Comment by corbinu** [comment]
I think it is good to go as a replacement. We can ways issue new versions if we decide we want to make more changes.

**Comment by ilyavolodin** [comment]
Awesome. Thanks @corbinu for driving this. I will publish a release in the next few days (or sooner), just so we could try it and see if any other changes needs to be made.

**Comment by soda0289** [comment]
Looking forward to using this in ESlint v4.0. It will fix some long standing issues with typescript parser and open the door to having more rules work as expected.

**Comment by ilyavolodin** [comment]
I just published it. New release version is v3.7.0. Let me know if you see any problems.
