### ISSUE TITLE
Proposal: define `node.parent` property in scope analysis

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint-scope#27]
ESLint is defining `node.parent` property while their AST traversing. This have caused confusing a bit because the `node.parent` property of nodes which are after the current node is not defined.

If we define the `node.parent` property in the traversing of scope analysis, we can resolve that confusing without extra cost.

Thoughts?

**Comment by ilyavolodin** [comment]
That sounds like a good solution. Since we are already traversing through the whole AST once for eslint-scope, we might as well apply `parent` property on the first pass.

**Comment by soda0289** [comment]
We should add parent property when visit() is called on a node, as this will help writing scope handlers.  I was confused why parent was set in some node and not others, but this makes sense. Thanks for the explanation.

If we want to only set parent property in eslint-scope, we need to make sure every node is traversed as eslint-scope will not visit the children when a visitor function is found. It is up to the scope handler to call visitChildren() which might not always be called.

**Comment by not-an-aardvark** [comment]
I think this is moot now because ESLint defines `node.parent` before rules run. Feel free to reopen if you disagree.
