### ISSUE TITLE
Proposal: Define an API to add nodes types to Referencer and hooks to Visit methods

### ISSUE THREAD

**Issue by soda0289** [eslint/eslint-scope#30]
Parsers such as typescript-eslint and babel-eslint have their own unique nodes which have their own properties and ways of defining scopes.

We can currently update VisitorKeys but this does not guarantee nodes will be added as a reference or scoped correctly. The visitorFallback function cannot solve the problem completely either. Some nodes might be scoped incorrectly because Identifier nodes could be definitions not just references, which is the default.

I believe we can solve this in two parts:

Allow new node type handlers too be passed into eslint-scope. Since we can already pass in our own set of VisitorKeys this would complement that well.

Allow for hooks/events to be called before and after a visit method is called.
Currently eslint-scope has the following visit methods:
- export declaration
- import declaration
- variable declaration
- function
- property
- pattern
- for in
- class

And two from esrecurse
- visit() - for nodes
- visitChildren() - for child nodes in VisitorKeys

This goal is for monkey patching to be removed from babel-eslint and for eslint rules such as no-unused-vars and no-undef to work as expected in typescript and babel/flow.

**Comment by not-an-aardvark** [comment]
Thanks, I like the ideas in this proposal. I have a few questions:

* If a parser can supply its own listeners, is there a reason to also allow hooks for existing listeners? I'm not sure I understand the motivation for the second part of the API. For example, it seems like instead of registering a hook for eslint-scope's `ImportDeclaration` listener, a parser could just add it's own `ImportDeclaration` listener.
* What types of things would hook functions be able to do? Ideally, we should be able to make modifications to the implementation of `eslint-scope` later on without breaking existing hooks.

**Comment by soda0289** [comment]
> If a parser can supply its own listeners, is there a reason to also allow hooks for existing listeners? I'm not sure I understand the motivation for the second part of the API. For example, it seems like instead of registering a hook for eslint-scope's ImportDeclaration listener, a parser could just add its own ImportDeclaration listener.

If the parser were to replace the node listener the existing logic would need to be copied over. This could be solved by allowing the parser to call into the original node listener. Similar to how super() works when extending methods. 
Hooks would still allow for the original logic to be run but could modify the scope/nodes before or after. I think it would be a simpler solution if we just allow listeners to be replaced as hooking in adds its own complexities.

Another consideration is that some node listeners are in multiple places depending on context. For example Identifier listener is in Referencer and PatternVisititor. If we replace them it should be in both places. We would have to define a way to determine current context.

> What types of things would hook functions be able to do? Ideally, we should be able to make modifications to the implementation of eslint-scope later on without breaking existing hooks.

We would need to define an API for hooks or node listeners, a lot of these functions are private. I still need to put more thought into exactly what would be made public. For a starting point:
- Creating a Scope
- Entering/Leaving current scope
- Adding a Reference
- Creating a Definition

If we only have node listeners that could be enough. But if we allow hooks we might want the hooks to be able to modify the current scope by adding or removing references or definitions. This would add more complexity and makes me believe that we should only allow replacing node listeners to start.

**Comment by not-an-aardvark** [comment]
I'm unsure about allowing listeners to be completely replaced, because it seems like that would require plugins to understand the semantics of existing listeners. That seems like it could cause some problems, e.g. if we want to allow multiple plugins to be enabled simultaneously without knowing about each other. Ideally, I think it would be best if plugins could add their own listeners that would get called *in addition* to any existing listeners (i.e. without replacement), but I'm unsure whether that's feasible implementation-wise.

**Comment by soda0289** [comment]
Having multiple listeners that do not conflict would be difficult. Since each plugin could not guarantee the state of a scope when it leaves its handler.

It might be better/easier to only allow one plugin or set of node listeners. Similar to how eslint can only use one parser. Since an eslint parser will be the one making the modifications it could work well for this case.

**Comment by soda0289** [comment]
It could be possible to allow multiple plugins/listeners if we could ensure that a Reference, Declaration, or Scope was only created once per node. This way even if multiple plugins tried to add the same Identifier node as a reference to a scope it would not create duplicates, which I think is what happens now.

I do think that allowing multiple plugins could make the code more module. Instead of having only a parser set node listeners we could have plugins for Decorators, Type Parameters, and Type Anotations

**Comment by hzoo** [comment]
Yeah this looks good to me!

In https://github.com/babel/babel-eslint/blob/master/index.js

- we have to reach in and modify the Definition/reference modules https://github.com/babel/babel-eslint/blob/f59d2009652e14acf1231a1268a8324cf046514e/index.js#L31-L39

```js
var escope = eslintMod.require("eslint-scope");
var Definition = eslintMod.require("eslint-scope/lib/definition").Definition;
var referencer = eslintMod.require("eslint-scope/lib/referencer");
```

- monkeypatch the original visitor methods: https://github.com/babel/babel-eslint/blob/f59d2009652e14acf1231a1268a8324cf046514e/index.js#L276-L288

by saving a reference to the previous function, adding some checks before the original function is called, and then calling it again.

```js
  var variableDeclaration = referencer.prototype.VariableDeclaration;
  referencer.prototype.VariableDeclaration = function(node) {
    if (node.declarations) {
      for (var i = 0; i < node.declarations.length; i++) {
        var id = node.declarations[i].id;
        var typeAnnotation = id.typeAnnotation;
        if (typeAnnotation) {
          checkIdentifierOrVisit.call(this, typeAnnotation);
        }
      }
    }
    variableDeclaration.call(this, node);
  };
```

- sometimes add a new scope definition with https://github.com/babel/babel-eslint/blob/f59d2009652e14acf1231a1268a8324cf046514e/index.js#L179-L194

**Comment by nzakas** [comment]
Closing due to age.
