### ISSUE TITLE
#39 affect global installations?

### ISSUE THREAD

**Issue by Frozenfire92** [eslint/eslint-scope#41]
I'm sure many others also have this question, and the relevant issue was closed so I will ask here

are global installations of eslint affected by #39 ?

**Comment by hugmanrique** [comment]
As the malware gets executed as a `preinstall` script, I would assume it does.

Also note no token will be leaked if you don't have a `.npmrc` file on your home dir (`~`).

This might change if the attacker changes the pastebin file contents on https://pastebin.com/XLeVP82h. Please, report it if you can.

**Comment by not-an-aardvark** [comment]
Yes, the issue affected global installations.
