### ISSUE TITLE
eslint-config-eslint compromised?

### ISSUE THREAD

**Issue by jwalton** [eslint/eslint-scope#43]
Hi!  This is a reply to the last comment [here](https://github.com/eslint/eslint-scope/issues/39#issuecomment-404560795), but unfortunately that thread is locked.

@kaicataldo what version of eslint-config-eslint was compromised?  Users can easily check to see if they've accidentally installed a bad version at some point in the past by looking in ~/.npm/eslint-config-eslint to see if the infected version is in their cache... but only if they know what the infected version number is.  :)

**Comment by MarshallOfSound** [comment]
Based on the version history the npm registry is reporting the now unpublished version was `5.0.2`

**Comment by kaicataldo** [comment]
The original issue has now been updated, but here's the issue for eslint-config-eslint specifically: https://github.com/eslint/eslint/issues/10600

**Comment by jwalton** [comment]
Thanks!
