### ISSUE TITLE
Please don't recommend LastPass

### ISSUE THREAD

**Issue by jhabdas** [eslint/eslint-scope#44]
From your post-mortem #39:

> Package maintainers and users should avoid reusing the same password across multiple different sites. A password manager like 1Password or LastPass can help with this.

Please reconsider recommendations of this nature as these are paid services and LastPass has a history of getting hacked.

Instead, consider using a sneakernet password manager like [KeePassX](https://keepassx.org/) instead or, if you like your password managers online and open source, use [BitWarden](https://bitwarden.com/)—recently removed from the [list of password managers wiki](https://en.wikipedia.org/wiki/List_of_password_managers) for reasons which I don't care to look into.

Thanks.

**Comment by not-an-aardvark** [comment]
After discussing this internally, there was a consensus that we don't want to make a change here, for a few reasons:

* We think including examples of password managers might make it more likely that someone unfamiliar with password managers will be able to get started with one.
* Our listing of a few password managers is not intended as an endorsement over their competitors; we're simply providing two of the most well-known options as examples. It's expected that users would need to do their own research if they want to make sure they choose the best option for themselves.

**Comment by jhabdas** [comment]
Thank you for your consideration.

**Comment by jhabdas** [comment]
> Consider promoting the FLOSS option, LessPass.

Thanks for sharing that one, I hadn't seen it yet and the folks on the [List of Password Managers Wiki](https://en.wikipedia.org/wiki/List_of_password_managers) [aren't making it easy](https://en.wikipedia.org/w/index.php?title=List_of_password_managers&action=history) for me to get other FLOSS options such as Bitwarden listed which TBH is the crux of this issue.

**Comment by jhabdas** [comment]
> Consider promoting the FLOSS option, [LessPass](https://lesspass.com/).

Thanks for sharing that one, I hadn't seen it yet and the folks on Wikipedia [aren't making it easy](https://en.wikipedia.org/w/index.php?title=List_of_password_managers&action=history) for me to get other FLOSS options such as Bitwarden listed which I've been working on now for over 6 months.

**Comment by jhabdas** [comment]
> Consider promoting the FLOSS option, [LessPass](https://lesspass.com/).

Thanks for sharing that one, I hadn't seen it yet and the folks on Wikipedia [aren't making it easy](https://en.wikipedia.org/w/index.php?title=List_of_password_managers&action=history) for me to get other FLOSS options such as Bitwarden listed which I've been attempting to do for over 6 months.

**Comment by jhabdas** [comment]
> Consider promoting the FLOSS option, [LessPass](https://lesspass.com/).

Thanks for sharing that one, I hadn't seen it yet and the folks on Wikipedia [aren't making it easy](https://en.wikipedia.org/w/index.php?title=List_of_password_managers&action=history) for me to get other FLOSS options such as Bitwarden listed which I've been attempting for many months.
