### ISSUE TITLE
Class variable is found both in the module/global scope and the class scope

### ISSUE THREAD

**Issue by futpib** [eslint/eslint-scope#48]
Consider the following code:
```js
class X {
  constructor() {
    console.log(X);
  }
};
console.log(X);
```

Or open https://astexplorer.net/#/gist/3a7a2b28e6098bc30ee7d16a4dabdbfc/3b9b700d7c8c40f4d9b1481ef940f532e1618b7c and open the browser console (the scopes should be logged there).

For this code, the `X` variable is found (in the `scope.set.has('X')` sense) in two scopes: 
1. The `module` (or `global`, depending on the parser's `sourceType`) scope with one reference (the top-level `console.log(X)` call)
2. The `class` scope with one reference (the `console.log(X)` call in the constructor)

I instead expected that the `X` variable is found in the upper scope only and that it has two references (for each `console.log(X)` call).
This is how it works with any other declaration (`function`/`var`/`let`/`const`)

**Comment by mysticatea** [comment]
Hi. Thank you for this issue.

That behavior is intentional. Let's consider the following case.

```js
class X {
  constructor() {
    console.log(X);
  }
}
const Y = X;
X = 0;
console.log(X); //→ 0
new Y(); //→ X
```

Even if we rewrite `X` in the upper scope, it doesn't affect the references of `X` in the class scope.
`eslint-scope` makes two variable objects to express this behavior.

**Comment by futpib** [comment]
Wow, thank you, I did not know they were actually separate scopes.
