### ISSUE TITLE
ArrowFunctionExpression's scope is always strict scope

### ISSUE THREAD

**Issue by futpib** [eslint/eslint-scope#49]
It seems to be deliberate that `eslint-scope` always sets `isStrict` to `true` for arrow function scopes. But this is not how it works in all the engines I could get my hands to.

I used assignment to an undeclared variable to check if the code is in strict mode:

With explicit strict mode, we get an error:
```bash
node -e '"use strict"; (() => { a = 5 })()'
# ReferenceError: a is not defined
```

Without `"use strict"` an error is not thrown, which means it's not in strict mode, but `eslint-scope` would treat the scope as strict anyway:
```bash
node -e '(() => { x = 1 })()'
```

I also checked with the spec's definition of strict mode code, and it seems that arrow functions should not get any special treatment (only classes should): https://www.ecma-international.org/ecma-262/#sec-strict-mode-code

https://github.com/eslint/eslint-scope/blob/3e69fdcf102082f3b3c419d0864d7ed90323f4ca/lib/scope.js#L52-L55

https://github.com/eslint/eslint-scope/blob/3e69fdcf102082f3b3c419d0864d7ed90323f4ca/tests/es6-arrow-function-expression.js#L55

**Comment by mysticatea** [comment]
Thank you for the report!

Sounds like a bug.
Are you willing to submit a pull request?

**Comment by not-an-aardvark** [comment]
Reopening because the fix was reverted (see https://github.com/eslint/eslint-scope/pull/51)
