### ISSUE TITLE
ImportDeclaration should appear when the mode is ES6 and in the module context

### ISSUE THREAD

**Issue by oneacik** [eslint/eslint-scope#55]
I'm using @typescript-eslint/parser in eslint for tsx files.
I have this code in .tsx file:

```ts
import React from 'react';

export class Wallboard extends React.Component<{ meetupGroups: [string] }> {
  constructor(props: Readonly<{ meetupGroups: [string] }>) {
    super(props);
  }

  render(): React.ReactElement {
    return <div>{'ksi'}</div>;
  }
}
```

and this configuration (+ big webpack configuration):

```json
{
  "parser": "babel-eslint",
  "extends": [
    "@jetbrains",
    "@jetbrains/eslint-config/browser",
    "@jetbrains/eslint-config/es6",
    "@jetbrains/eslint-config/node",
    "@jetbrains/eslint-config/react",
    "@jetbrains/eslint-config/angular",
    "@jetbrains/eslint-config/test"
  ],

  "overrides": [
    {
      "files": ["**/*.ts", "**/*.tsx"],
      "parser": "@typescript-eslint/parser",
      "plugins": ["@typescript-eslint"],
      "extends": [
        "@jetbrains",
        "@jetbrains/eslint-config/browser",
        "@jetbrains/eslint-config/es6",
        "@jetbrains/eslint-config/node",
        "@jetbrains/eslint-config/react",
        "@jetbrains/eslint-config/angular",
        "@jetbrains/eslint-config/test"
      ],
      "settings": {
        "import/resolver": {
          "node": {
            "extensions": [".js",".jsx",".ts",".tsx"]
          }
        }
      }
    }
  ]
}
```

and I get this error:

> /Users/psuwala/projects/hs3/event-monitor/src/components/Wallboard.tsx
>   0:0  error  Parsing error: ImportDeclaration should appear when the mode is ES6 and in the module context

I pinpointed that it comes from here:

https://github.com/eslint/eslint-scope/blame/dbddf14d5771b21b5da704213e4508c660ca1c64/lib/referencer.js#L577

of course if I remove `this.scopeManager.isModule()` it will work.

Any idea if it is possible to override it? Or is it typescript-eslint misuse?

**Comment by kaicataldo** [comment]
Have you tried specifying `ecmaVersion` To `2015` or higher In your configuration? While neither `babel-eslint` or `@typescript-eslint/parser` require it, the scope manager is passed this.

**Comment by oneacik** [comment]
I solved it currently by adding:
>   "parserOptions": {
>     "ecmaVersion": 6,
>     "sourceType": "module"
>   },

>     "ecmaVersion": 2015,
didn't solve it.

I wonder if this workaround is acceptable.

**Comment by kaicataldo** [comment]
Apologies for the lack of clarity about having to put this config in `parserOptions` -what you did is what I was suggesting (ESLint accepts `2015` or `6`). :+1:

**Comment by kaicataldo** [comment]
Closing this since this question has been answered.

**Comment by noahehall** [comment]
for anyone else following https://json.schemastore.org/eslintrc.json

dont use `ecmaVersion: latest`

use `ecmaVersion: 12` or something else

**Comment by HunterKohler** [comment]
@noahehall My savior. I don't know why Schemastore is wrong.
