### ISSUE TITLE
[suggest] improve compatibility with more estree parsers?

### ISSUE THREAD

**Issue by 3cp** [eslint/eslint-scope#58]
I am trying to use eslint-scope with [meriyah](https://github.com/meriyah/meriyah) which uses different data structure for ranges.

It doesn't have `.range: [start, end]`, but has direct `.start` and `.end`.

https://github.com/eslint/eslint-scope/blob/dbddf14d5771b21b5da704213e4508c660ca1c64/lib/scope.js#L711-L718

If I update the above code from `.range[0]` to `.start`, everything works fine with meriyah.

Do you consider to improve compatibility with other estree parsers? To check both `.range[0]` and `.start`? Thanks!

FYI, estree spec seems didn't define the shape of ranges, it only defined position. https://github.com/estree/estree/blob/14df8a024956ea289bd55b9c2226a1d5b8a473ee/es5.md#node-objects

**Comment by aladdin-add** [comment]
I'm not sure we can go that way, as `.start/.end` is non-standard and non-recommended.

Related issue(s): [RFC25](https://github.com/eslint/rfcs/blob/master/designs/2019-rule-tester-improvements/README.md), eslint/eslint#12096, eslint/eslint#12955

**Comment by 3cp** [comment]
Oh, thx! I did not know it got that much complications.

**Comment by 3cp** [comment]
I noticed it is acknowledged that both `.range` and `.start` `.end` are non-standard. Same as what I read from estree spec. https://github.com/eslint/eslint/issues/8956

**Comment by 3cp** [comment]
I think there is an opportunity to improve.

It's not about `.range[0]` or `.start`. I felt this check is doable even without any ranges information, because we knew where the node was (in params or body).

The reason of using ranges to check, is that the `reference` and `definition` objects didn't retain that information (in params or body). I am not sure how to retain that information in nested function scopes.

I could not get my head around the code base to come up a solution. But I think it's possible to totally remove the usage of `.range[0]`.

**Comment by bradzacher** [comment]
If you're looking for a completely estree-compliant version, isn't that what [`escope`](https://github.com/estools/escope) is?

**Comment by 3cp** [comment]
I came here to find an update-to-date version of escope 😄

**Comment by nzakas** [comment]
As mentioned previously, the start and stop properties are not part of ESTree. They only appear in Espree because we are built on Acorn, which adds these nonstandard properties. Removing them incurs a performance penalty so we leave them in place. However, we don’t rely on those properties being present and always use range internally.

Because we don’t want to encourage relying on nonstandard properties, we won’t be updating this package to use start and end.

Thanks!

**Comment by 3cp** [comment]
> But I think it's possible to totally remove the usage of .range[0].

@nzakas you probably missed my comment on reopening of the issue.
