### ISSUE TITLE
Is a class's heritage referenced from the wrong scope?

### ISSUE THREAD

**Issue by bradzacher** [eslint/eslint-scope#59]
Am I misunderstanding the spec here?
I'm new to attempting to read the ECMAScript spec, so I wouldn't be surprised if I'm wrong...

To me it looks like the superclass is referenced from within the class's scope:

https://www.ecma-international.org/ecma-262/8.0/#sec-runtime-semantics-classdefinitionevaluation

1) Let `lex` be the `LexicalEnvironment` of the running execution context.
2) Let `classScope` be `NewDeclarativeEnvironment(lex)`.
3) ...
4) If `className` is not `undefined`, then
  a) ...
5) If `ClassHeritage_opt` is not present, then
  a) ...
6) Else,
  a) Set the running execution context's `LexicalEnvironment` to `classScope`.
  b) Let `superclass` be the result of evaluating `ClassHeritage`.
  c) ...
7) ...

When `superclass` is evaluated, it is specifically within `classScope`. So this means the reference should be placed within the class scope, right?

However, the scope manager references the superclass before it nests the class scope (i.e. it is referenced from the parent's scope):

https://github.com/eslint/eslint-scope/blob/dbddf14d5771b21b5da704213e4508c660ca1c64/lib/referencer.js#L264-L280

----

I tried to dig through the old escope history, but there's no information attached to the commit (https://github.com/estools/escope/commit/c3e23e2c7fbbc49a9048871334069a8532e90c8d)

**Comment by nzakas** [comment]
I think the only answer we can give here is we don't know. We forked escope in order to have a better way to get it updated to fit in with our release cycle, but we still don't know all the dark secrets contained within.

**Comment by bradzacher** [comment]
It's not a huge deal ultimately - there's still a reference to it, and I don't think anyone consuming this package is explicitly asserting a reference comes from a specific scope.

I was just working on a ground-up reimplementation which supports typescript (https://github.com/typescript-eslint/typescript-eslint/pull/1939) and noticed this. I have some snapshot tests to validate the structure of the scope. When I added a snapshot test for the heritage, I noticed the placement of the reference and was confused.

I was mainly hoping someone more familiar with the spec could tell me if I'm interpreting the JS spec correctly or not 😅

**Comment by mysticatea** [comment]
I'm sorry for my overlooked.

I think @bradzacher is right. The references of the `extends` clause should be in the class scope. Therefore, in the following rare case:

```js
const A = class A extends A {}
```

the third `A` must be resolved to the second `A` rather than the first `A`. But, the current `eslint-scope` resolves it to the first `A`. It looks like a bug.

**Comment by nzakas** [comment]
@mysticatea is this something you feel like addressing? If not, I can try to do it

**Comment by mdjermanovic** [comment]
@nzakas are you maybe working on this? If not, I could take it.

**Comment by nzakas** [comment]
I'm not. Please feel free.

**Comment by mdjermanovic** [comment]
I'm working on this.
