### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by gaborantal** [eslint/eslint-scope#66]
I just tried to run the provided code from README. However there are several problems: the first is that `eslintScope.analyze` requires a second parameter called `providedOptions`.

The second problem is a **TypeError**:
```
D:\path-to-project\node_modules\eslint-scope\lib\scope.js:711
        const bodyStart = this.block.body.range[0];
                                               ^

TypeError: Cannot read property '0' of undefined
    at FunctionScope.__isValidResolution (D:\path-to-project\node_modules\eslint-scope\lib\scope.js:711:48)
    at FunctionScope.__resolve (D:\path-to-project\node_modules\eslint-scope\lib\scope.js:357:19)
    at FunctionScope.__staticCloseRef (D:\path-to-project\node_modules\eslint-scope\lib\scope.js:294:19)
    at FunctionScope.__close (D:\path-to-project\node_modules\eslint-scope\lib\scope.js:336:22)
    at Referencer.close (D:\path-to-project\node_modules\eslint-scope\lib\referencer.js:129:68)
    at Referencer.visitFunction (D:\path-to-project\node_modules\eslint-scope\lib\referencer.js:261:14)
    at Referencer.ArrowFunctionExpression (D:\path-to-project\node_modules\eslint-scope\lib\referencer.js:573:14)
    at Referencer.Visitor.visit (D:\path-to-project\node_modules\esrecurse\esrecurse.js:104:34)
    at Referencer.Visitor.visitChildren (D:\path-to-project\node_modules\esrecurse\esrecurse.js:83:38)
    at Referencer.CallExpression (D:\path-to-project\node_modules\eslint-scope\lib\referencer.js:500:14)

Process finished with exit code 1
```

My used **dependencies** are (from package.json):
```
  "dependencies": {
    "eslint-scope": "^5.1.1",
    "espree": "^7.3.0",
    "estraverse": "^5.2.0"
  }
```
**Versions**:
node --version
v12.19.0
npm --version
6.14.8

My full code (I was just fiddling around to test something):
```
const eslintScope = require('eslint-scope');
const espree = require('espree');
const estraverse = require('estraverse');

code = `
function alma() {
    console.log("sh");
}
const materials = [
  'Hydrogen',
  'Helium',
  'Lithium',
  'Beryllium'
];

console.log(materials.map(material => material.length));
class Car {
  constructor(brand) {
    this._carname = brand;
  }
  get carname() {
    return this._carname;
  }
  set carname(x) {
    this._carname = x;
  }
}

let mycar = new Car("Ford");
mycar.carname = "Volvo";
`;


const ast = espree.parse(code, { ecmaVersion: 2021, loc: true, });
console.log(ast);
var scopeManager = eslintScope.analyze(ast, {});

var currentScope = scopeManager.acquire(ast);   // global scope

estraverse.traverse(ast, {
    enter: function(node, parent) {
        // do stuff

        if (/Function/.test(node.type)) {
            currentScope = scopeManager.acquire(node);  // get current function scope
        }
    },
    leave: function(node, parent) {
        if (/Function/.test(node.type)) {
            currentScope = currentScope.upper;  // set to parent scope
        }

        // do stuff
    }
});
console.log(ast);
```

**Comment by mdjermanovic** [comment]
Hi @gaborantal, thanks for the issue!

 > the first is that eslintScope.analyze requires a second parameter called providedOptions
> ```js
> var scopeManager = eslintScope.analyze(ast, {});
> ```

It isn't technically required, `eslintScope.analyze(ast)` works without the second argument (I've just tried) and uses [default options](https://github.com/eslint/eslint-scope/blob/8a7a21cce3a4bf17753d588f6444742235566a92/lib/index.js#L65).

Though, it's true that you should probably always provide options, like `ecmaVersion` etc. See for example how ESLint calls `eslintScope.analyze` [here](https://github.com/eslint/eslint/blob/d973675a5c06a2bd4f8ce640c78b67842cfebfd4/lib/linter/linter.js#L611).

> The second problem is a TypeError
>
> ```
> D:\path-to-project\node_modules\eslint-scope\lib\scope.js:711
>        const bodyStart = this.block.body.range[0];
>                                               ^
>
> TypeError: Cannot read property '0' of undefined
> ```
>
> ```js
> const ast = espree.parse(code, { ecmaVersion: 2021, loc: true, });
> ```

This should be `range: true`, `eslint-scope` doesn't use `loc`.

I think it would be good to add `{ range: true }` to the README example.

**Comment by gaborantal** [comment]
@mdjermanovic Yup, thanks, that solved my problem, it works like a charm now. I am also on your opinion, these should've been in the sample in README. I'd like to notice that it would've been better to use let/const/etc in the sample codes. If you don't mind, I'll send a PR with this change.

(the loc is intented to used by my future function that will be implemented.)

**Comment by nzakas** [comment]
@gaborantal feel free to submit a PR.
