### ISSUE TITLE
Convert package to ESM

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint-scope#70]
To convert this package from CommonJS to ECMAScript modules (ESM):

- [ ] Add `type: module` to `package.json`
- [ ] Convert files in `lib` to ESM
- [ ] Convert files in `tests/lib` to ESM
- [ ] Upgrade Mocha
- [ ] Create `build` script in `package.json` to generate CommonJS file (`.cjs`) in `dist` directory (use Rollup)
- [ ] Add `dist` to `.gitignore`
- [ ] Run `build` in `prepare` script in `package.json` to ensure build is run at key moments
- [ ] Update `package.json` so that `main` points in the CJS file in `dist` and `exports` provides both `require` and `import` options
- [ ] Update README instructions

**Comment by brettz9** [comment]
Would you like to change to named exports here too?

**Comment by nzakas** [comment]
Sure, I'm open to that.

**Comment by brettz9** [comment]
FWIW, in my PR I've kept some single item files as default exports, but for the main one (the one being exported) and others, they are named.

**Comment by aladdin-add** [comment]
as I mentioned [here](https://github.com/eslint/espree/issues/501#issuecomment-856651098), eslint-scope was used by webpack, too. the change would stop webpack upgrading to the latest eslint-scope. // @sokra

**Comment by nzakas** [comment]
@aladdin-add would it stop them from upgrading, or would they just wait a bit longer? I assume with a breaking change that it would probably go through a more thorough evaluation before upgrading regardless.

**Comment by aladdin-add** [comment]
yes, they will drop Node.js < 12 at some point, it's just a bit longer.
