### ISSUE TITLE
require() of ES modules is not supported

### ISSUE THREAD

**Issue by Robloche** [eslint/eslint-scope#77]
Since eslint updated to v8.0.0, I get the following error:

```0:0  error  Parsing error: Must use import to load ES Module: /home/vsts/work/1/s/node_modules/eslint-scope/lib/definition.js
require() of ES modules is not supported.
require() of /home/vsts/work/1/s/node_modules/eslint-scope/lib/definition.js from /home/vsts/work/1/s/node_modules/babel-eslint/lib/require-from-eslint.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename definition.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/vsts/work/1/s/node_modules/eslint-scope/package.json```

**Comment by jais-shivam** [comment]
Facing this error any potential solution?

Parsing error: require() of ES Module G:\DAPP\Fund\fund_transfer\node_modules\eslint-scope\lib\index.js from G:\DAPP\Fund\fund_transfer\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in G:\DAPP\Fund\fund_transfer\node_modules\eslint-scope\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

**Comment by mdjermanovic** [comment]
@jais-shivam

> Parsing error: require() of ES Module G:\DAPP\Fund\fund_transfer\node_modules\eslint-scope\lib\index.js from G:\DAPP\Fund\fund_transfer\node_modules\babel-eslint\lib\require-from-eslint.js not supported.

You are using deprecated [`babel-eslint`](https://www.npmjs.com/package/babel-eslint). Please try with [`@babel/eslint-parser`](https://www.npmjs.com/package/@babel/eslint-parser).

**Comment by jais-shivam** [comment]
> @jais-shivam
> 
> > Parsing error: require() of ES Module G:\DAPP\Fund\fund_transfer\node_modules\eslint-scope\lib\index.js from G:\DAPP\Fund\fund_transfer\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
> 
> You are using deprecated [`babel-eslint`](https://www.npmjs.com/package/babel-eslint). Please try with [`@babel/eslint-parser`](https://www.npmjs.com/package/@babel/eslint-parser).

@mdjermanovic 
I am still getting same error though my application is running now but my compiler is still throwing that error .
![image](https://user-images.githubusercontent.com/47588402/169688226-57bd7509-8049-4e08-b25a-1bc24e50c08a.png)

**Comment by mdjermanovic** [comment]
> > @jais-shivam
> > > Parsing error: require() of ES Module G:\DAPP\Fund\fund_transfer\node_modules\eslint-scope\lib\index.js from G:\DAPP\Fund\fund_transfer\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
> > 
> > 
> > You are using deprecated [`babel-eslint`](https://www.npmjs.com/package/babel-eslint). Please try with [`@babel/eslint-parser`](https://www.npmjs.com/package/@babel/eslint-parser).
> 
> @mdjermanovic I am still getting the same error though my application is running now, my compiler is still throwing that error. ![image](https://user-images.githubusercontent.com/47588402/169688226-57bd7509-8049-4e08-b25a-1bc24e50c08a.png)

This is still coming from the `babel-eslint` package (see node_modules\\**babel-eslint**\\ in the screenshot). Did you set `parser: "@babel/eslint-parser"` in your ESLint config file?

https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser#setup

**Comment by jais-shivam** [comment]
> > > @jais-shivam
> > > > Parsing error: require() of ES Module G:\DAPP\Fund\fund_transfer\node_modules\eslint-scope\lib\index.js from G:\DAPP\Fund\fund_transfer\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
> > > 
> > > 
> > > You are using deprecated [`babel-eslint`](https://www.npmjs.com/package/babel-eslint). Please try with [`@babel/eslint-parser`](https://www.npmjs.com/package/@babel/eslint-parser).
> > 
> > @mdjermanovic I am still getting the same error though my application is running now, my compiler is still throwing that error. ![image](https://user-images.githubusercontent.com/47588402/169688226-57bd7509-8049-4e08-b25a-1bc24e50c08a.png)
> 
> This is still coming from the `babel-eslint` package (see node_modules\\**babel-eslint**\\ in the screenshot). Did you set `parser: "@babel/eslint-parser"` in your ESLint config file?
> 
> https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser#setup

Thank you @mdjermanovic my problem is resolved thanks for your help🙏

**Comment by sampriti026** [comment]
Hey @jais-shivam How did you resolve it? Can you please share me the steps?

**Comment by DavidOliver** [comment]
@sampriti026, [see the instructions here](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser#babeleslint-parser---).

Also:

```bash
$ npm uninstall babel-eslint
```

Alternatively, if you don't need/want to use babel's parser, you can instead [let ESLint use its default parser](https://eslint.org/docs/latest/user-guide/configuring/plugins#specifying-parser) by not setting `parser` at all in the `.eslintrc` files.

**Comment by rami-alloush** [comment]
Why ember still uses `babel-eslint`? Am I missing something?

**Comment by SashoStzPakAz** [comment]
I had the same issue, and fixed with updating the .eslintrc.js file with the following:
```
  parserOptions: {
    parser: "@babel/eslint-parser"
  },
```

**Comment by Tareq1586** [comment]
> @jais-shivam
> 
> > Parsing error: require() of ES Module G:\DAPP\Fund\fund_transfer\node_modules\eslint-scope\lib\index.js from G:\DAPP\Fund\fund_transfer\node_modules\babel-eslint\lib\require-from-eslint.js not supported.
> 
> You are using deprecated [`babel-eslint`](https://www.npmjs.com/package/babel-eslint). Please try with [`@babel/eslint-parser`](https://www.npmjs.com/package/@babel/eslint-parser).

Cool

**Comment by PainKillerOFC** [comment]
This helped me also. I needed to delete **package-lock** and **yarn.lock**
![image](https://github.com/eslint/eslint-scope/assets/87381160/e263917f-8f4f-4f3e-a13d-05ae19f7a98e)
