### ISSUE TITLE
Support for `ecmaVersion: latest`

### ISSUE THREAD

**Issue by ota-meshi** [eslint/eslint-scope#78]
Currently ESLint resolves `ecmaVersion: latest` only when using espree, so` "latest" `is passed to eslint-scope when using a different parser.

https://github.com/eslint/eslint/blob/3630211c46f1ed691445231164e29e5cd6c87dff/lib/linter/linter.js#L449-L454

I want eslint-scope to support `ecmaVersion: "latest"`.
(Should I open this issue in the ESLint repo?)

Related to https://github.com/vuejs/vue-eslint-parser/issues/135

**Comment by ota-meshi** [comment]
I found a duplicate issue #74. So I close this issue.

**Comment by ota-meshi** [comment]
I reopen this issue. I saw #74, but babel-parser seems to be using eslint-scope by calling it from the parser.
I expect scopes using vue-eslint-parser to be resolved within eslint.
What do you think should be done in this case?

**Comment by nzakas** [comment]
As stated in https://github.com/eslint/eslint-scope/issues/74#issuecomment-898780125, you can safely set ecmaVersion to 6 all the time.

**Comment by ota-meshi** [comment]
@nzakas Thank you for your reply. But I'm still not sure.
How do I pass the ecmaVersion to the eslint-scope called by eslint?
Does that mean letting ESLint users use `ecmaVersion: 6`?

**Comment by ota-meshi** [comment]
vue-eslint-parser, unlike babel and typescript-eslint, does not provide a scope manager from the parser.

**Comment by nzakas** [comment]
Oh I see, I misunderstood. ESLint doesn’t interpret parserOptions when Espree isn’t used because we can’t know what other parsers are expecting as values. “Latest” is understood only by Espree. 

For people using custom parsers, they should set parserOptions.ecmaVersion to a number and not “latest”. We expect custom parsers to validate their own parserOptions.

**Comment by ota-meshi** [comment]
Thank you for your reply. I could understand how eslint works.
What do you think is best for vue-eslint-parser to support `ecmaVersion: latest`?
Do you think the parser should provide its own scopeManager like typescript-eslint?

**Comment by ota-meshi** [comment]
As additional information, vue-eslint-parser can understand and parse `ecmaVersion: latest`. However, it cannot actually be used with ESLint because it fails with eslint-scope.

**Comment by nzakas** [comment]
Hmmmm. In that case, maybe we can just change ESLint so it always passes ecmaVersion: 6 to eslint-scope. I don’t think it will cause any issues and will allow your use case to work.

**Comment by ota-meshi** [comment]
Thank you for your opinion! I will open an issue in ESLint repo later.

**Comment by nzakas** [comment]
I was wrong. There are some other differences between ecmaVersion 5 and 6, so we can't just set it to 6. However, this is a problem we should address in ESLint rather than on eslint-scope. Thanks!
